name: 'GH-ACTION-ALIYUN-OSS'
description: 'A github action for uploading assets to aliyun oss via convinient configuration.'
inputs:
  access-key-id:
    description: 'The accessKeyId for accessing aliyun oss'
    required: true
  access-key-secret:
    description: 'The accessKeySecret for accessing aliyun oss'
    required: true
  bucket:
    description: 'The bucket name of aliyun oss'
    required: true
  region:
    description: 'The region name of aliyun oss'
    required: true
  dest-path:
    description: 'The remote destination in aliyun oss for storage'
    required: true
  local-path:
    description: 'The local path that you wanna upload to aliyun oss'
    required: true
outputs:
  uploaded-files:
    description: 'The uploaded files'
runs:
  using: 'node12'
  main: 'dist/index.js'
